# **Pricing Elasticity Analysis**

### Importing Libraries

In [1]:
import pandas as pd 
import numpy as np

### Importing Dataset

In [2]:
merged_df = pd.read_csv("../data/merged/merged_dataset.csv")
display(merged_df.head())

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,price,competitor_price,discount_percentage,sales_date,market_average_value_x,market_average_value_y,avg_market_sales_x,avg_market_quantity_x,avg_market_sales_y,avg_market_quantity_y
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,130.9800,137.529000,0.0,11/8/2016,0.0,0.0,0.0,0.0,NaN,NaN
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,243.9800,256.179000,0.0,11/8/2016,0.0,0.0,0.0,0.0,NaN,NaN
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,7.3100,7.675500,0.0,6/12/2016,0.0,0.0,0.0,0.0,NaN,NaN
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,191.5155,201.091275,45.0,10/11/2015,0.0,0.0,0.0,0.0,NaN,NaN
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,11.1840,11.743200,20.0,10/11/2015,0.0,0.0,0.0,0.0,NaN,NaN

### Price Elasticity Analysis

In [3]:
elasticity_df = merged_df.copy()

### Sort Data Before Analysis

In [4]:
elasticity_df = elasticity_df.sort_values(
    by='sales_date'
)

### Calculate Percentage Changes

In [5]:
elasticity_df['price_change_pct'] = (
    elasticity_df['price']
    .pct_change()
)

elasticity_df['quantity_change_pct'] = (
    elasticity_df['units_sold']
    .pct_change()
)

### Calculate Elasticity

In [6]:
elasticity_df['elasticity'] = (
    elasticity_df['quantity_change_pct'] /
    elasticity_df['price_change_pct']
)

### Handle Invalid Values

In [7]:
elasticity_df.replace(
    [np.inf, -np.inf],
    0,
    inplace=True
)

elasticity_df.fillna(0, inplace=True)

### Elasticity Category

In [8]:
elasticity_df['elasticity_category'] = (
    elasticity_df['elasticity']
    .apply(
        lambda x:
        'Highly Elastic'
        if abs(x) > 1
        else 'Inelastic'
    )
)

### Result

In [9]:
display(
    elasticity_df[
        [
            'product_name',
            'price',
            'units_sold',
            'elasticity',
            'elasticity_category'
        ]
    ].head()
)

,product_name,price,units_sold,elasticity,elasticity_category
8074,"Pressboard Covers with Storage Hooks, 9 1/2"" x...",0.982,14,0.000000,Inelastic
848,"Linden 10"" Round Wall Clock, Black",12.224,4,-0.062394,Inelastic
8075,Fellowes Superior 10 Outlet Split Surge Protector,7.612,2,1.325239,Highly Elastic
8073,GBC Instant Report Kit,1.294,5,-1.807217,Highly Elastic
8071,Office Star - Contemporary Task Swivel Chair,77.686,4,-0.003388,Inelastic